# Generated by Django 4.0.3 on 2022-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Py', 'Python'), ('Js', 'JavaScript'), ('R', 'R Language'), ('Go', 'GoLang'), ('C++', 'CPlusPlus'), ('SQL', 'Structured Query Language'), ('HTML', 'Hypertext Mark Up Language'), ('CSS', 'Cascading Style Sheet')], max_length=4)),
                ('framework', models.CharField(choices=[('DJ', 'Django'), ('FL', 'Flask'), ('RJs', 'ReactJs'), ('EJS', 'ExpressJs'), ('NJS', 'NodeJs'), ('MUI', 'Material-UI'), ('TWC', 'TailWindCss'), ('BTS', 'BootStrap')], max_length=4)),
                ('level', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='project description')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(choices=[('PR', 'private'), ('PB', 'public')], max_length=2)),
            ],
        ),
    ]
