# Generated by Django 4.0.3 on 2022-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
