# Generated by Django 4.0.3 on 2022-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
