# Generated by Django 4.0.3 on 2022-03-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectsmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='slug',
        ),
    ]
