# Generated by Django 4.0.3 on 2022-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectsmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='languages_supported',
            field=models.ManyToManyField(to='projects.programlanguagemodel'),
        ),
    ]
