# Generated by Django 4.0.3 on 2022-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectsmodel_languages_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlanguagemodel',
            name='framework',
            field=models.CharField(choices=[('NN', 'None'), ('DJ', 'Django'), ('FL', 'Flask'), ('RJs', 'ReactJs'), ('EJS', 'ExpressJs'), ('NJS', 'NodeJs'), ('MUI', 'Material-UI'), ('TWC', 'TailWindCss'), ('BTS', 'BootStrap')], max_length=4),
        ),
    ]
