# Generated by Django 4.0.3 on 2022-03-28 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_programlanguagemodel_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
