# Generated by Django 4.0.3 on 2022-03-23 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(help_text='social media', max_length=50)),
                ('media_url', models.URLField(blank=True, max_length=300, null=True)),
                ('media_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PS', 'PrimarySchool'), ('HS', 'HighSchool'), ('UN', 'University')], max_length=2)),
                ('name', models.CharField(help_text='institution name', max_length=50)),
                ('certificate', models.CharField(choices=[('KCSE', 'Kenya Certificate of Primary Education'), ('KCSE', 'Kenya Certificate of Secondary Education'), ('BSDE', 'Bachelors Degree')], max_length=4)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('date_completed', models.DateField(default=datetime.date(2022, 3, 23))),
            ],
        ),
        migrations.CreateModel(
            name='HirerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Jarib', max_length=15)),
                ('middle_name', models.CharField(default='Ngonzo', max_length=15)),
                ('last_name', models.CharField(default='Wetshi', max_length=15)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(default='Congolese', max_length=15)),
                ('occupation', models.CharField(default='BackEnd Developer', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Py', 'Python'), ('Js', 'JavaScript'), ('R', 'R Language'), ('Go', 'GoLang'), ('C++', 'CPlusPlus'), ('SQL', 'Structured Query Language'), ('HTML', 'Hypertext Mark Up Language'), ('CSS', 'Cascading Style Sheet')], max_length=4)),
                ('framework', models.CharField(choices=[('DJ', 'Django'), ('FL', 'Flask'), ('RJs', 'ReactJs'), ('EJS', 'ExpressJs'), ('NJS', 'NodeJs'), ('MUI', 'Material-UI'), ('TWC', 'TailWindCss'), ('BTS', 'BootStrap')], max_length=4)),
                ('level', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='project description')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(choices=[('PR', 'private'), ('PB', 'public')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RefereeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('level', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_api.projectsmodel')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_api.refereemodel')),
            ],
        ),
    ]
