# Generated by Django 4.0.3 on 2022-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0002_alter_educationmodel_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='occupation',
            field=models.CharField(default='BackEnd Developer', max_length=50),
        ),
    ]
