# Generated by Django 4.0.3 on 2022-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0003_alter_personalinfo_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile-pic'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='certificate',
            field=models.CharField(choices=[('KCPE', 'Kenya Certificate of Primary Education'), ('KCSE', 'Kenya Certificate of Secondary Education'), ('BSDE', 'Bachelors Degree')], max_length=4),
        ),
    ]
