# Generated by Django 4.0.3 on 2022-03-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0004_personalinfo_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HirerModel',
        ),
        migrations.DeleteModel(
            name='ProgramLanguageModel',
        ),
        migrations.RemoveField(
            model_name='workexperiencemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workexperiencemodel',
            name='referee',
        ),
        migrations.DeleteModel(
            name='ProjectsModel',
        ),
        migrations.DeleteModel(
            name='RefereeModel',
        ),
        migrations.DeleteModel(
            name='WorkExperienceModel',
        ),
    ]
