# Generated by Django 4.0.3 on 2022-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_api', '0005_delete_hirermodel_delete_programlanguagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='certificate_image',
            field=models.ImageField(null=True, upload_to='certificates'),
        ),
    ]
